# Generated by Django 5.2.7 on 2025-11-05 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['region', 'name'], 'verbose_name': 'Tuman', 'verbose_name_plural': 'Tumanlar'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['district__region__name', 'district__name', 'name'], 'verbose_name': 'Joy', 'verbose_name_plural': 'Joylar'},
        ),
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['place'], 'verbose_name': 'Joy rasmi', 'verbose_name_plural': 'Joy rasmlari'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Viloyat', 'verbose_name_plural': 'Viloyatlar'},
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('region', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('district', 'name')},
        ),
    ]
